version: "3"
services:
   mongo:
      container_name: mongo-mern-docker-genxiot
      image: mongo
      restart: always
      ports:
         - "27017:27018"
      networks:
         - default
      volumes:
         - ./server/docker-setup/mongo/db-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
         - ./server/docker-setup/mongo/mongo-volume:/data/db
      environment:
         - MONGO_INITDB_DATABASE=genxiot
         - MONGO_INITDB_USER=local_user
         - MONGO_INITDB_PASSWORD=Password123

   backend:
      container_name: node-mern-docker-genxiot
      build:
         context: ./server
         dockerfile: docker-setup/node/development/Dockerfile
      networks:
         - default
         - frontend
      volumes:
         - ./server:/home/node/app
      environment:
         - NODE_ENV=development
      env_file:
         - ./server/.env.development
      tty: true
      stdin_open: true
      depends_on:
         - mongo
         - mosquitto
      ports:
         - "8080:8080"

   frontend:
      container_name: react-mern-docker-genxiot
      build:
         context: ./client
         dockerfile: docker-setup/react/development/Dockerfile
      networks:
         - frontend
      environment:
         - NODE_ENV=development
      volumes:
         - ./client:/frontend
        
      depends_on:
         - backend
      tty: true
      stdin_open: true
      ports:
         - "3000:3000"



   mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto
      restart: always
      volumes:
         - ./mosquitto/config:/mosquitto/config
         - ./mosquitto/config:/mosquitto/data
         - ./mosquitto/config:/mosquitto/log
      ports:
         - 1883:1883
         - 9001:9001
    

networks:
  default:
    name: backend-network-mern-docker-genxiot
  frontend:
    name: frontend-network-mern-docker-genxiot
